var userName = "Pulkit Porwal";
var marvelHeros = ["Iron Man", "Thor", "Black Widow", "Captain America"];
var typeAny;
typeAny = 5;
var userAge = 17;
var isStudent = true;
console.log(userName);
console.log(userAge);
console.log(isStudent);
console.log(typeAny);
console.log(marvelHeros);
